p <-read.csv.sql("household_power_consumption.txt", sql = "select * from file WHERE Date IN ('1/2/2007','2/2/2007')", header = TRUE, sep = ";")
par(mfrow =c(2,2)) 
plot(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Global_active_power, xlab="",ylab="Global Active Power (kilowatts)",type="l")
plot(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Voltage, xlab="datetime",ylab="Voltage",type="l")
plot(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Sub_metering_1, xlab="",ylab="Global Active Power (kilowatts)",type="l")
points(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Sub_metering_2,col="red", type ="l" )
points(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Sub_metering_3,col="blue", type ="l" )
legend("topright",pch = 3, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(as.POSIXct(paste(p$Date,p$Time), format="%d/%m/%Y %H:%M:%S"),p$Global_reactive_power, xlab="datetime",ylab="Global_reactive_power",type="l")